### ISSUE TITLE
Facing this error while npm install 

### ISSUE THREAD

**Issue by krunalvictra** [smarty/smartystreets-javascript-sdk-react-example#21]
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin"} (current: {"os":"win32"})
npm ERR! notsup Valid os:  darwin
npm ERR! notsup Actual os: win32

can you please help me out?

**Comment by ducanbeu** [comment]
We are not able to replicate this issue on our side. If you continue to see this issue, you may try updating your version of NPM followed by reaching out to our Smarty Support team for assistance if the issue persists.

**Comment by ducanbeu** [comment]
We are not able to replicate this issue on our side. If you continue to see this issue, you may try updating your version of NPM followed by reaching out to our Smarty Support team for assistance if the issue persists.

**Comment by kdalkema** [comment]
I'm seeing this issue also
